name: "PWM LED Controller"
version: "1.0.6"
slug: "pwm_led"
description: "Управление на LED чрез PWM на GPIO 12 за Raspberry Pi 5"
arch:
  - aarch64
startup: application
boot: auto
host_network: true
devices:
  - /dev/gpiochip4
  - /dev/mem:/dev/mem
gpio: true
options: {}
schema: {}
