name: "PWM LED Controller"
version: "2.1.1"
slug: "pwm_led"
description: "Управление на LED чрез PWM на GPIO за Raspberry Pi 5 (gpiod + sysfs)"
arch:
  - aarch64
startup: application
boot: auto
devices:
  - /dev/gpiochip4
  - /sys/class/pwm:/sys/class/pwm:rw
  - /dev/mem:/dev/mem
