name: "PWM LED Controller"
version: "1.0.10"
slug: "pwm_led"
description: "Управление на PWM на GPIO 12 за Raspberry Pi 5"
arch:
  - aarch64
startup: application
boot: auto
host_network: true
full_access: true
gpio: true
options:
  duty_cycle: 50
  frequency: 26000
  auto_start: true
schema:
  duty_cycle: "int(10,100)"
  frequency: "int(1000,100000)"
  auto_start: "bool"
